// Code generated by mockery. DO NOT EDIT.

package collection_account_route

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// CollectionAccountRouteHandlerIF is an autogenerated mock type for the CollectionAccountRouteHandlerIF type
type CollectionAccountRouteHandlerIF struct {
	mock.Mock
}

type CollectionAccountRouteHandlerIF_Expecter struct {
	mock *mock.Mock
}

func (_m *CollectionAccountRouteHandlerIF) EXPECT() *CollectionAccountRouteHandlerIF_Expecter {
	return &CollectionAccountRouteHandlerIF_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: context
func (_m *CollectionAccountRouteHandlerIF) Create(context echo.Context) error {
	ret := _m.Called(context)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(context)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CollectionAccountRouteHandlerIF_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type CollectionAccountRouteHandlerIF_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context echo.Context
func (_e *CollectionAccountRouteHandlerIF_Expecter) Create(context interface{}) *CollectionAccountRouteHandlerIF_Create_Call {
	return &CollectionAccountRouteHandlerIF_Create_Call{Call: _e.mock.On("Create", context)}
}

func (_c *CollectionAccountRouteHandlerIF_Create_Call) Run(run func(context echo.Context)) *CollectionAccountRouteHandlerIF_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *CollectionAccountRouteHandlerIF_Create_Call) Return(_a0 error) *CollectionAccountRouteHandlerIF_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CollectionAccountRouteHandlerIF_Create_Call) RunAndReturn(run func(echo.Context) error) *CollectionAccountRouteHandlerIF_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Disable provides a mock function with given fields: context
func (_m *CollectionAccountRouteHandlerIF) Disable(context echo.Context) error {
	ret := _m.Called(context)

	if len(ret) == 0 {
		panic("no return value specified for Disable")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(context)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CollectionAccountRouteHandlerIF_Disable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Disable'
type CollectionAccountRouteHandlerIF_Disable_Call struct {
	*mock.Call
}

// Disable is a helper method to define mock.On call
//   - context echo.Context
func (_e *CollectionAccountRouteHandlerIF_Expecter) Disable(context interface{}) *CollectionAccountRouteHandlerIF_Disable_Call {
	return &CollectionAccountRouteHandlerIF_Disable_Call{Call: _e.mock.On("Disable", context)}
}

func (_c *CollectionAccountRouteHandlerIF_Disable_Call) Run(run func(context echo.Context)) *CollectionAccountRouteHandlerIF_Disable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *CollectionAccountRouteHandlerIF_Disable_Call) Return(_a0 error) *CollectionAccountRouteHandlerIF_Disable_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CollectionAccountRouteHandlerIF_Disable_Call) RunAndReturn(run func(echo.Context) error) *CollectionAccountRouteHandlerIF_Disable_Call {
	_c.Call.Return(run)
	return _c
}

// NewCollectionAccountRouteHandlerIF creates a new instance of CollectionAccountRouteHandlerIF. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCollectionAccountRouteHandlerIF(t interface {
	mock.TestingT
	Cleanup(func())
}) *CollectionAccountRouteHandlerIF {
	mock := &CollectionAccountRouteHandlerIF{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
