// Code generated by mockery. DO NOT EDIT.

package capture_flow

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// PaymentCaptureUseCaseIF is an autogenerated mock type for the PaymentCaptureUseCaseIF type
type PaymentCaptureUseCaseIF struct {
	mock.Mock
}

type PaymentCaptureUseCaseIF_Expecter struct {
	mock *mock.Mock
}

func (_m *PaymentCaptureUseCaseIF) EXPECT() *PaymentCaptureUseCaseIF_Expecter {
	return &PaymentCaptureUseCaseIF_Expecter{mock: &_m.Mock}
}

// CapturePayment provides a mock function with given fields: ctx, orderID, paymentID
func (_m *PaymentCaptureUseCaseIF) CapturePayment(ctx context.Context, orderID string, paymentID string) error {
	ret := _m.Called(ctx, orderID, paymentID)

	if len(ret) == 0 {
		panic("no return value specified for CapturePayment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, orderID, paymentID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PaymentCaptureUseCaseIF_CapturePayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CapturePayment'
type PaymentCaptureUseCaseIF_CapturePayment_Call struct {
	*mock.Call
}

// CapturePayment is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID string
//   - paymentID string
func (_e *PaymentCaptureUseCaseIF_Expecter) CapturePayment(ctx interface{}, orderID interface{}, paymentID interface{}) *PaymentCaptureUseCaseIF_CapturePayment_Call {
	return &PaymentCaptureUseCaseIF_CapturePayment_Call{Call: _e.mock.On("CapturePayment", ctx, orderID, paymentID)}
}

func (_c *PaymentCaptureUseCaseIF_CapturePayment_Call) Run(run func(ctx context.Context, orderID string, paymentID string)) *PaymentCaptureUseCaseIF_CapturePayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *PaymentCaptureUseCaseIF_CapturePayment_Call) Return(_a0 error) *PaymentCaptureUseCaseIF_CapturePayment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PaymentCaptureUseCaseIF_CapturePayment_Call) RunAndReturn(run func(context.Context, string, string) error) *PaymentCaptureUseCaseIF_CapturePayment_Call {
	_c.Call.Return(run)
	return _c
}

// NewPaymentCaptureUseCaseIF creates a new instance of PaymentCaptureUseCaseIF. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentCaptureUseCaseIF(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentCaptureUseCaseIF {
	mock := &PaymentCaptureUseCaseIF{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
