// Code generated by mockery. DO NOT EDIT.

package capture_flow

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// PaymentReleaseUseCaseIF is an autogenerated mock type for the PaymentReleaseUseCaseIF type
type PaymentReleaseUseCaseIF struct {
	mock.Mock
}

type PaymentReleaseUseCaseIF_Expecter struct {
	mock *mock.Mock
}

func (_m *PaymentReleaseUseCaseIF) EXPECT() *PaymentReleaseUseCaseIF_Expecter {
	return &PaymentReleaseUseCaseIF_Expecter{mock: &_m.Mock}
}

// ReleasePayment provides a mock function with given fields: ctx, orderID, paymentID, reason
func (_m *PaymentReleaseUseCaseIF) ReleasePayment(ctx context.Context, orderID string, paymentID string, reason string) error {
	ret := _m.Called(ctx, orderID, paymentID, reason)

	if len(ret) == 0 {
		panic("no return value specified for ReleasePayment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, orderID, paymentID, reason)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PaymentReleaseUseCaseIF_ReleasePayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReleasePayment'
type PaymentReleaseUseCaseIF_ReleasePayment_Call struct {
	*mock.Call
}

// ReleasePayment is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID string
//   - paymentID string
//   - reason string
func (_e *PaymentReleaseUseCaseIF_Expecter) ReleasePayment(ctx interface{}, orderID interface{}, paymentID interface{}, reason interface{}) *PaymentReleaseUseCaseIF_ReleasePayment_Call {
	return &PaymentReleaseUseCaseIF_ReleasePayment_Call{Call: _e.mock.On("ReleasePayment", ctx, orderID, paymentID, reason)}
}

func (_c *PaymentReleaseUseCaseIF_ReleasePayment_Call) Run(run func(ctx context.Context, orderID string, paymentID string, reason string)) *PaymentReleaseUseCaseIF_ReleasePayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *PaymentReleaseUseCaseIF_ReleasePayment_Call) Return(_a0 error) *PaymentReleaseUseCaseIF_ReleasePayment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PaymentReleaseUseCaseIF_ReleasePayment_Call) RunAndReturn(run func(context.Context, string, string, string) error) *PaymentReleaseUseCaseIF_ReleasePayment_Call {
	_c.Call.Return(run)
	return _c
}

// NewPaymentReleaseUseCaseIF creates a new instance of PaymentReleaseUseCaseIF. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentReleaseUseCaseIF(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentReleaseUseCaseIF {
	mock := &PaymentReleaseUseCaseIF{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
