// Code generated by mockery. DO NOT EDIT.

package capture

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// CaptureHandlerIF is an autogenerated mock type for the CaptureHandlerIF type
type CaptureHandlerIF struct {
	mock.Mock
}

type CaptureHandlerIF_Expecter struct {
	mock *mock.Mock
}

func (_m *CaptureHandlerIF) EXPECT() *CaptureHandlerIF_Expecter {
	return &CaptureHandlerIF_Expecter{mock: &_m.Mock}
}

// CapturePayment provides a mock function with given fields: context
func (_m *CaptureHandlerIF) CapturePayment(context echo.Context) error {
	ret := _m.Called(context)

	if len(ret) == 0 {
		panic("no return value specified for CapturePayment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(context)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CaptureHandlerIF_CapturePayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CapturePayment'
type CaptureHandlerIF_CapturePayment_Call struct {
	*mock.Call
}

// CapturePayment is a helper method to define mock.On call
//   - context echo.Context
func (_e *CaptureHandlerIF_Expecter) CapturePayment(context interface{}) *CaptureHandlerIF_CapturePayment_Call {
	return &CaptureHandlerIF_CapturePayment_Call{Call: _e.mock.On("CapturePayment", context)}
}

func (_c *CaptureHandlerIF_CapturePayment_Call) Run(run func(context echo.Context)) *CaptureHandlerIF_CapturePayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *CaptureHandlerIF_CapturePayment_Call) Return(_a0 error) *CaptureHandlerIF_CapturePayment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CaptureHandlerIF_CapturePayment_Call) RunAndReturn(run func(echo.Context) error) *CaptureHandlerIF_CapturePayment_Call {
	_c.Call.Return(run)
	return _c
}

// NewCaptureHandlerIF creates a new instance of CaptureHandlerIF. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCaptureHandlerIF(t interface {
	mock.TestingT
	Cleanup(func())
}) *CaptureHandlerIF {
	mock := &CaptureHandlerIF{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
