image: public.ecr.aws/docker/library/golang:1.23

include:
  - project: 'clubhub.ai1/organization/platform/modules/ci-workflows'
    ref: 'feat/ci-cd-eks'
    file: '/backend/go/templates/stages-migrate.yml'

.go-cache:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  cache:
    paths:
      - .go/pkg/mod/

variables:
  OUTPUT_NAME: __bin__/$CI_PROJECT_NAME
  MIN_COVERAGE_PERCENT: 50
  RUN_DEPLOY: "true"
  CD_SCOPE: "application"
  CD_DEFAULT_BRANCH: 'main'
  CD_REPOSITORY: "application-definitions"
  CD_REPOSITORY_PATH: "clubhub.ai1/organization/platform/gitops/application-definitions.git"

after_script:
  - echo "Ending CI"
before_script:
  - echo "Starting CI"
  - apk update && apk upgrade && apk --no-cache add ca-certificates bash git gcc g++ pkgconfig build-base zlib-dev  pkgconf openssh
  - mkdir /root/.ssh/
  - echo "$SSH_PRIVATE_KEY" > /root/.ssh/id_rsa && chmod 400 /root/.ssh/id_rsa
  - touch /root/.ssh/known_hosts
  - ssh-keyscan gitlab.com >> /root/.ssh/known_hosts
  - git config --global url."git@gitlab.com:".insteadOf "https://gitlab.com/"
  - go mod download && go mod verify