// Code generated by mockery. DO NOT EDIT.

package usecases

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	request "gitlab.com/clubhub.ai1/organization/backend/payments-api/internal/infra/api/handler/card/dto/request"
	response "gitlab.com/clubhub.ai1/organization/backend/payments-api/internal/infra/api/handler/card/dto/response"
)

// DeleteCardUsecaseIF is an autogenerated mock type for the DeleteCardUsecaseIF type
type DeleteCardUsecaseIF struct {
	mock.Mock
}

type DeleteCardUsecaseIF_Expecter struct {
	mock *mock.Mock
}

func (_m *DeleteCardUsecaseIF) EXPECT() *DeleteCardUsecaseIF_Expecter {
	return &DeleteCardUsecaseIF_Expecter{mock: &_m.Mock}
}

// DeleteCard provides a mock function with given fields: ctx, _a1, enterpriseId
func (_m *DeleteCardUsecaseIF) DeleteCard(ctx context.Context, _a1 request.DeleteCardRequest, enterpriseId string) (response.DeleteCardResponse, error) {
	ret := _m.Called(ctx, _a1, enterpriseId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCard")
	}

	var r0 response.DeleteCardResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, request.DeleteCardRequest, string) (response.DeleteCardResponse, error)); ok {
		return rf(ctx, _a1, enterpriseId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, request.DeleteCardRequest, string) response.DeleteCardResponse); ok {
		r0 = rf(ctx, _a1, enterpriseId)
	} else {
		r0 = ret.Get(0).(response.DeleteCardResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, request.DeleteCardRequest, string) error); ok {
		r1 = rf(ctx, _a1, enterpriseId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteCardUsecaseIF_DeleteCard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCard'
type DeleteCardUsecaseIF_DeleteCard_Call struct {
	*mock.Call
}

// DeleteCard is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 request.DeleteCardRequest
//   - enterpriseId string
func (_e *DeleteCardUsecaseIF_Expecter) DeleteCard(ctx interface{}, _a1 interface{}, enterpriseId interface{}) *DeleteCardUsecaseIF_DeleteCard_Call {
	return &DeleteCardUsecaseIF_DeleteCard_Call{Call: _e.mock.On("DeleteCard", ctx, _a1, enterpriseId)}
}

func (_c *DeleteCardUsecaseIF_DeleteCard_Call) Run(run func(ctx context.Context, _a1 request.DeleteCardRequest, enterpriseId string)) *DeleteCardUsecaseIF_DeleteCard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(request.DeleteCardRequest), args[2].(string))
	})
	return _c
}

func (_c *DeleteCardUsecaseIF_DeleteCard_Call) Return(_a0 response.DeleteCardResponse, _a1 error) *DeleteCardUsecaseIF_DeleteCard_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DeleteCardUsecaseIF_DeleteCard_Call) RunAndReturn(run func(context.Context, request.DeleteCardRequest, string) (response.DeleteCardResponse, error)) *DeleteCardUsecaseIF_DeleteCard_Call {
	_c.Call.Return(run)
	return _c
}

// NewDeleteCardUsecaseIF creates a new instance of DeleteCardUsecaseIF. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeleteCardUsecaseIF(t interface {
	mock.TestingT
	Cleanup(func())
}) *DeleteCardUsecaseIF {
	mock := &DeleteCardUsecaseIF{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
