// Code generated by mockery. DO NOT EDIT.

package usecases

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	request "gitlab.com/clubhub.ai1/organization/backend/payments-api/internal/infra/api/handler/payment_method/dto/request"
	response "gitlab.com/clubhub.ai1/organization/backend/payments-api/internal/infra/api/handler/payment_method/dto/response"
)

// PaymentMethodUseCasesIF is an autogenerated mock type for the PaymentMethodUseCasesIF type
type PaymentMethodUseCasesIF struct {
	mock.Mock
}

type PaymentMethodUseCasesIF_Expecter struct {
	mock *mock.Mock
}

func (_m *PaymentMethodUseCasesIF) EXPECT() *PaymentMethodUseCasesIF_Expecter {
	return &PaymentMethodUseCasesIF_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, _a1, enterpriseId
func (_m *PaymentMethodUseCasesIF) Create(ctx context.Context, _a1 request.PaymentMethodRequest, enterpriseId string) (response.PaymentMethodResponse, error) {
	ret := _m.Called(ctx, _a1, enterpriseId)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 response.PaymentMethodResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, request.PaymentMethodRequest, string) (response.PaymentMethodResponse, error)); ok {
		return rf(ctx, _a1, enterpriseId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, request.PaymentMethodRequest, string) response.PaymentMethodResponse); ok {
		r0 = rf(ctx, _a1, enterpriseId)
	} else {
		r0 = ret.Get(0).(response.PaymentMethodResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, request.PaymentMethodRequest, string) error); ok {
		r1 = rf(ctx, _a1, enterpriseId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PaymentMethodUseCasesIF_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type PaymentMethodUseCasesIF_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 request.PaymentMethodRequest
//   - enterpriseId string
func (_e *PaymentMethodUseCasesIF_Expecter) Create(ctx interface{}, _a1 interface{}, enterpriseId interface{}) *PaymentMethodUseCasesIF_Create_Call {
	return &PaymentMethodUseCasesIF_Create_Call{Call: _e.mock.On("Create", ctx, _a1, enterpriseId)}
}

func (_c *PaymentMethodUseCasesIF_Create_Call) Run(run func(ctx context.Context, _a1 request.PaymentMethodRequest, enterpriseId string)) *PaymentMethodUseCasesIF_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(request.PaymentMethodRequest), args[2].(string))
	})
	return _c
}

func (_c *PaymentMethodUseCasesIF_Create_Call) Return(_a0 response.PaymentMethodResponse, _a1 error) *PaymentMethodUseCasesIF_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PaymentMethodUseCasesIF_Create_Call) RunAndReturn(run func(context.Context, request.PaymentMethodRequest, string) (response.PaymentMethodResponse, error)) *PaymentMethodUseCasesIF_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewPaymentMethodUseCasesIF creates a new instance of PaymentMethodUseCasesIF. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentMethodUseCasesIF(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentMethodUseCasesIF {
	mock := &PaymentMethodUseCasesIF{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
