// Code generated by mockery. DO NOT EDIT.

package aws

import (
	context "context"

	s3 "github.com/aws/aws-sdk-go-v2/service/s3"
	mock "github.com/stretchr/testify/mock"
)

// S3Client is an autogenerated mock type for the S3Client type
type S3Client struct {
	mock.Mock
}

type S3Client_Expecter struct {
	mock *mock.Mock
}

func (_m *S3Client) EXPECT() *S3Client_Expecter {
	return &S3Client_Expecter{mock: &_m.Mock}
}

// PutObject provides a mock function with given fields: ctx, params
func (_m *S3Client) PutObject(ctx context.Context, params *s3.PutObjectInput) (*s3.PutObjectOutput, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for PutObject")
	}

	var r0 *s3.PutObjectOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *s3.PutObjectInput) (*s3.PutObjectOutput, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *s3.PutObjectInput) *s3.PutObjectOutput); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3.PutObjectOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *s3.PutObjectInput) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// S3Client_PutObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutObject'
type S3Client_PutObject_Call struct {
	*mock.Call
}

// PutObject is a helper method to define mock.On call
//   - ctx context.Context
//   - params *s3.PutObjectInput
func (_e *S3Client_Expecter) PutObject(ctx interface{}, params interface{}) *S3Client_PutObject_Call {
	return &S3Client_PutObject_Call{Call: _e.mock.On("PutObject", ctx, params)}
}

func (_c *S3Client_PutObject_Call) Run(run func(ctx context.Context, params *s3.PutObjectInput)) *S3Client_PutObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*s3.PutObjectInput))
	})
	return _c
}

func (_c *S3Client_PutObject_Call) Return(_a0 *s3.PutObjectOutput, _a1 error) *S3Client_PutObject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *S3Client_PutObject_Call) RunAndReturn(run func(context.Context, *s3.PutObjectInput) (*s3.PutObjectOutput, error)) *S3Client_PutObject_Call {
	_c.Call.Return(run)
	return _c
}

// NewS3Client creates a new instance of S3Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewS3Client(t interface {
	mock.TestingT
	Cleanup(func())
}) *S3Client {
	mock := &S3Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
