// Code generated by mockery. DO NOT EDIT.

package collection_account

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// CollectionAccountHandlerIF is an autogenerated mock type for the CollectionAccountHandlerIF type
type CollectionAccountHandlerIF struct {
	mock.Mock
}

type CollectionAccountHandlerIF_Expecter struct {
	mock *mock.Mock
}

func (_m *CollectionAccountHandlerIF) EXPECT() *CollectionAccountHandlerIF_Expecter {
	return &CollectionAccountHandlerIF_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: context
func (_m *CollectionAccountHandlerIF) Create(context echo.Context) error {
	ret := _m.Called(context)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(context)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CollectionAccountHandlerIF_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type CollectionAccountHandlerIF_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context echo.Context
func (_e *CollectionAccountHandlerIF_Expecter) Create(context interface{}) *CollectionAccountHandlerIF_Create_Call {
	return &CollectionAccountHandlerIF_Create_Call{Call: _e.mock.On("Create", context)}
}

func (_c *CollectionAccountHandlerIF_Create_Call) Run(run func(context echo.Context)) *CollectionAccountHandlerIF_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *CollectionAccountHandlerIF_Create_Call) Return(_a0 error) *CollectionAccountHandlerIF_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CollectionAccountHandlerIF_Create_Call) RunAndReturn(run func(echo.Context) error) *CollectionAccountHandlerIF_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewCollectionAccountHandlerIF creates a new instance of CollectionAccountHandlerIF. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCollectionAccountHandlerIF(t interface {
	mock.TestingT
	Cleanup(func())
}) *CollectionAccountHandlerIF {
	mock := &CollectionAccountHandlerIF{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
