// Code generated by mockery. DO NOT EDIT.

package repositories

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entities "gitlab.com/clubhub.ai1/organization/backend/payments-api/internal/infra/repositories/collection_account/entities"
)

// CollectionAccountReadRepositoryIF is an autogenerated mock type for the CollectionAccountReadRepositoryIF type
type CollectionAccountReadRepositoryIF struct {
	mock.Mock
}

type CollectionAccountReadRepositoryIF_Expecter struct {
	mock *mock.Mock
}

func (_m *CollectionAccountReadRepositoryIF) EXPECT() *CollectionAccountReadRepositoryIF_Expecter {
	return &CollectionAccountReadRepositoryIF_Expecter{mock: &_m.Mock}
}

// GetCollectionAccountRoute provides a mock function with given fields: ctx, country, associatedOrigin, currency, enterpriseId
func (_m *CollectionAccountReadRepositoryIF) GetCollectionAccountRoute(ctx context.Context, country string, associatedOrigin string, currency string, enterpriseId string) (entities.CollectionAccountEntity, error) {
	ret := _m.Called(ctx, country, associatedOrigin, currency, enterpriseId)

	if len(ret) == 0 {
		panic("no return value specified for GetCollectionAccountRoute")
	}

	var r0 entities.CollectionAccountEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) (entities.CollectionAccountEntity, error)); ok {
		return rf(ctx, country, associatedOrigin, currency, enterpriseId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) entities.CollectionAccountEntity); ok {
		r0 = rf(ctx, country, associatedOrigin, currency, enterpriseId)
	} else {
		r0 = ret.Get(0).(entities.CollectionAccountEntity)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = rf(ctx, country, associatedOrigin, currency, enterpriseId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CollectionAccountReadRepositoryIF_GetCollectionAccountRoute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCollectionAccountRoute'
type CollectionAccountReadRepositoryIF_GetCollectionAccountRoute_Call struct {
	*mock.Call
}

// GetCollectionAccountRoute is a helper method to define mock.On call
//   - ctx context.Context
//   - country string
//   - associatedOrigin string
//   - currency string
//   - enterpriseId string
func (_e *CollectionAccountReadRepositoryIF_Expecter) GetCollectionAccountRoute(ctx interface{}, country interface{}, associatedOrigin interface{}, currency interface{}, enterpriseId interface{}) *CollectionAccountReadRepositoryIF_GetCollectionAccountRoute_Call {
	return &CollectionAccountReadRepositoryIF_GetCollectionAccountRoute_Call{Call: _e.mock.On("GetCollectionAccountRoute", ctx, country, associatedOrigin, currency, enterpriseId)}
}

func (_c *CollectionAccountReadRepositoryIF_GetCollectionAccountRoute_Call) Run(run func(ctx context.Context, country string, associatedOrigin string, currency string, enterpriseId string)) *CollectionAccountReadRepositoryIF_GetCollectionAccountRoute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *CollectionAccountReadRepositoryIF_GetCollectionAccountRoute_Call) Return(_a0 entities.CollectionAccountEntity, _a1 error) *CollectionAccountReadRepositoryIF_GetCollectionAccountRoute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CollectionAccountReadRepositoryIF_GetCollectionAccountRoute_Call) RunAndReturn(run func(context.Context, string, string, string, string) (entities.CollectionAccountEntity, error)) *CollectionAccountReadRepositoryIF_GetCollectionAccountRoute_Call {
	_c.Call.Return(run)
	return _c
}

// NewCollectionAccountReadRepositoryIF creates a new instance of CollectionAccountReadRepositoryIF. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCollectionAccountReadRepositoryIF(t interface {
	mock.TestingT
	Cleanup(func())
}) *CollectionAccountReadRepositoryIF {
	mock := &CollectionAccountReadRepositoryIF{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
