// Code generated by mockery. DO NOT EDIT.

package repositories

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entities "gitlab.com/clubhub.ai1/organization/backend/payments-api/internal/domain/entities"
)

// CollectionCenterRepositoryIF is an autogenerated mock type for the CollectionCenterRepositoryIF type
type CollectionCenterRepositoryIF struct {
	mock.Mock
}

type CollectionCenterRepositoryIF_Expecter struct {
	mock *mock.Mock
}

func (_m *CollectionCenterRepositoryIF) EXPECT() *CollectionCenterRepositoryIF_Expecter {
	return &CollectionCenterRepositoryIF_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, collectionCenter
func (_m *CollectionCenterRepositoryIF) Create(ctx context.Context, collectionCenter entities.CollectionCenterEntity) error {
	ret := _m.Called(ctx, collectionCenter)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.CollectionCenterEntity) error); ok {
		r0 = rf(ctx, collectionCenter)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CollectionCenterRepositoryIF_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type CollectionCenterRepositoryIF_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - collectionCenter entities.CollectionCenterEntity
func (_e *CollectionCenterRepositoryIF_Expecter) Create(ctx interface{}, collectionCenter interface{}) *CollectionCenterRepositoryIF_Create_Call {
	return &CollectionCenterRepositoryIF_Create_Call{Call: _e.mock.On("Create", ctx, collectionCenter)}
}

func (_c *CollectionCenterRepositoryIF_Create_Call) Run(run func(ctx context.Context, collectionCenter entities.CollectionCenterEntity)) *CollectionCenterRepositoryIF_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entities.CollectionCenterEntity))
	})
	return _c
}

func (_c *CollectionCenterRepositoryIF_Create_Call) Return(_a0 error) *CollectionCenterRepositoryIF_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CollectionCenterRepositoryIF_Create_Call) RunAndReturn(run func(context.Context, entities.CollectionCenterEntity) error) *CollectionCenterRepositoryIF_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id, enterpriseId
func (_m *CollectionCenterRepositoryIF) FindByID(ctx context.Context, id string, enterpriseId string) (entities.CollectionCenterEntity, error) {
	ret := _m.Called(ctx, id, enterpriseId)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 entities.CollectionCenterEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (entities.CollectionCenterEntity, error)); ok {
		return rf(ctx, id, enterpriseId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) entities.CollectionCenterEntity); ok {
		r0 = rf(ctx, id, enterpriseId)
	} else {
		r0 = ret.Get(0).(entities.CollectionCenterEntity)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, id, enterpriseId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CollectionCenterRepositoryIF_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type CollectionCenterRepositoryIF_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - enterpriseId string
func (_e *CollectionCenterRepositoryIF_Expecter) FindByID(ctx interface{}, id interface{}, enterpriseId interface{}) *CollectionCenterRepositoryIF_FindByID_Call {
	return &CollectionCenterRepositoryIF_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id, enterpriseId)}
}

func (_c *CollectionCenterRepositoryIF_FindByID_Call) Run(run func(ctx context.Context, id string, enterpriseId string)) *CollectionCenterRepositoryIF_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *CollectionCenterRepositoryIF_FindByID_Call) Return(_a0 entities.CollectionCenterEntity, _a1 error) *CollectionCenterRepositoryIF_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CollectionCenterRepositoryIF_FindByID_Call) RunAndReturn(run func(context.Context, string, string) (entities.CollectionCenterEntity, error)) *CollectionCenterRepositoryIF_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewCollectionCenterRepositoryIF creates a new instance of CollectionCenterRepositoryIF. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCollectionCenterRepositoryIF(t interface {
	mock.TestingT
	Cleanup(func())
}) *CollectionCenterRepositoryIF {
	mock := &CollectionCenterRepositoryIF{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
