// Code generated by mockery. DO NOT EDIT.

package repositories

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entities "gitlab.com/clubhub.ai1/organization/backend/payments-api/internal/domain/entities"
)

// PaymentMethodRepositoryIF is an autogenerated mock type for the PaymentMethodRepositoryIF type
type PaymentMethodRepositoryIF struct {
	mock.Mock
}

type PaymentMethodRepositoryIF_Expecter struct {
	mock *mock.Mock
}

func (_m *PaymentMethodRepositoryIF) EXPECT() *PaymentMethodRepositoryIF_Expecter {
	return &PaymentMethodRepositoryIF_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, entity
func (_m *PaymentMethodRepositoryIF) Create(ctx context.Context, entity entities.PaymentMethodEntity) error {
	ret := _m.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.PaymentMethodEntity) error); ok {
		r0 = rf(ctx, entity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PaymentMethodRepositoryIF_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type PaymentMethodRepositoryIF_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - entity entities.PaymentMethodEntity
func (_e *PaymentMethodRepositoryIF_Expecter) Create(ctx interface{}, entity interface{}) *PaymentMethodRepositoryIF_Create_Call {
	return &PaymentMethodRepositoryIF_Create_Call{Call: _e.mock.On("Create", ctx, entity)}
}

func (_c *PaymentMethodRepositoryIF_Create_Call) Run(run func(ctx context.Context, entity entities.PaymentMethodEntity)) *PaymentMethodRepositoryIF_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entities.PaymentMethodEntity))
	})
	return _c
}

func (_c *PaymentMethodRepositoryIF_Create_Call) Return(_a0 error) *PaymentMethodRepositoryIF_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PaymentMethodRepositoryIF_Create_Call) RunAndReturn(run func(context.Context, entities.PaymentMethodEntity) error) *PaymentMethodRepositoryIF_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewPaymentMethodRepositoryIF creates a new instance of PaymentMethodRepositoryIF. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentMethodRepositoryIF(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentMethodRepositoryIF {
	mock := &PaymentMethodRepositoryIF{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
