// Code generated by mockery. DO NOT EDIT.

package group

import (
	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"
)

// OrderRoutesIF is an autogenerated mock type for the OrderRoutesIF type
type OrderRoutesIF struct {
	mock.Mock
}

type OrderRoutesIF_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderRoutesIF) EXPECT() *OrderRoutesIF_Expecter {
	return &OrderRoutesIF_Expecter{mock: &_m.Mock}
}

// Resource provides a mock function with given fields: c
func (_m *OrderRoutesIF) Resource(c *echo.Group) {
	_m.Called(c)
}

// OrderRoutesIF_Resource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resource'
type OrderRoutesIF_Resource_Call struct {
	*mock.Call
}

// Resource is a helper method to define mock.On call
//   - c *echo.Group
func (_e *OrderRoutesIF_Expecter) Resource(c interface{}) *OrderRoutesIF_Resource_Call {
	return &OrderRoutesIF_Resource_Call{Call: _e.mock.On("Resource", c)}
}

func (_c *OrderRoutesIF_Resource_Call) Run(run func(c *echo.Group)) *OrderRoutesIF_Resource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*echo.Group))
	})
	return _c
}

func (_c *OrderRoutesIF_Resource_Call) Return() *OrderRoutesIF_Resource_Call {
	_c.Call.Return()
	return _c
}

func (_c *OrderRoutesIF_Resource_Call) RunAndReturn(run func(*echo.Group)) *OrderRoutesIF_Resource_Call {
	_c.Run(run)
	return _c
}

// NewOrderRoutesIF creates a new instance of OrderRoutesIF. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderRoutesIF(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderRoutesIF {
	mock := &OrderRoutesIF{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
