// Code generated by mockery. DO NOT EDIT.

package group

import (
	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"
)

// PaymentMethodRoutesIF is an autogenerated mock type for the PaymentMethodRoutesIF type
type PaymentMethodRoutesIF struct {
	mock.Mock
}

type PaymentMethodRoutesIF_Expecter struct {
	mock *mock.Mock
}

func (_m *PaymentMethodRoutesIF) EXPECT() *PaymentMethodRoutesIF_Expecter {
	return &PaymentMethodRoutesIF_Expecter{mock: &_m.Mock}
}

// Resource provides a mock function with given fields: c
func (_m *PaymentMethodRoutesIF) Resource(c *echo.Group) {
	_m.Called(c)
}

// PaymentMethodRoutesIF_Resource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resource'
type PaymentMethodRoutesIF_Resource_Call struct {
	*mock.Call
}

// Resource is a helper method to define mock.On call
//   - c *echo.Group
func (_e *PaymentMethodRoutesIF_Expecter) Resource(c interface{}) *PaymentMethodRoutesIF_Resource_Call {
	return &PaymentMethodRoutesIF_Resource_Call{Call: _e.mock.On("Resource", c)}
}

func (_c *PaymentMethodRoutesIF_Resource_Call) Run(run func(c *echo.Group)) *PaymentMethodRoutesIF_Resource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*echo.Group))
	})
	return _c
}

func (_c *PaymentMethodRoutesIF_Resource_Call) Return() *PaymentMethodRoutesIF_Resource_Call {
	_c.Call.Return()
	return _c
}

func (_c *PaymentMethodRoutesIF_Resource_Call) RunAndReturn(run func(*echo.Group)) *PaymentMethodRoutesIF_Resource_Call {
	_c.Run(run)
	return _c
}

// NewPaymentMethodRoutesIF creates a new instance of PaymentMethodRoutesIF. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentMethodRoutesIF(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentMethodRoutesIF {
	mock := &PaymentMethodRoutesIF{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
