// Code generated by mockery. DO NOT EDIT.

package group

import (
	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"
)

// PaymentConceptRoutesIF is an autogenerated mock type for the PaymentConceptRoutesIF type
type PaymentConceptRoutesIF struct {
	mock.Mock
}

type PaymentConceptRoutesIF_Expecter struct {
	mock *mock.Mock
}

func (_m *PaymentConceptRoutesIF) EXPECT() *PaymentConceptRoutesIF_Expecter {
	return &PaymentConceptRoutesIF_Expecter{mock: &_m.Mock}
}

// Resource provides a mock function with given fields: c
func (_m *PaymentConceptRoutesIF) Resource(c *echo.Group) {
	_m.Called(c)
}

// PaymentConceptRoutesIF_Resource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resource'
type PaymentConceptRoutesIF_Resource_Call struct {
	*mock.Call
}

// Resource is a helper method to define mock.On call
//   - c *echo.Group
func (_e *PaymentConceptRoutesIF_Expecter) Resource(c interface{}) *PaymentConceptRoutesIF_Resource_Call {
	return &PaymentConceptRoutesIF_Resource_Call{Call: _e.mock.On("Resource", c)}
}

func (_c *PaymentConceptRoutesIF_Resource_Call) Run(run func(c *echo.Group)) *PaymentConceptRoutesIF_Resource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*echo.Group))
	})
	return _c
}

func (_c *PaymentConceptRoutesIF_Resource_Call) Return() *PaymentConceptRoutesIF_Resource_Call {
	_c.Call.Return()
	return _c
}

func (_c *PaymentConceptRoutesIF_Resource_Call) RunAndReturn(run func(*echo.Group)) *PaymentConceptRoutesIF_Resource_Call {
	_c.Run(run)
	return _c
}

// NewPaymentConceptRoutesIF creates a new instance of PaymentConceptRoutesIF. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentConceptRoutesIF(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentConceptRoutesIF {
	mock := &PaymentConceptRoutesIF{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
