// Code generated by mockery. DO NOT EDIT.

package group

import (
	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"
)

// WebhooksRoutesIF is an autogenerated mock type for the WebhooksRoutesIF type
type WebhooksRoutesIF struct {
	mock.Mock
}

type WebhooksRoutesIF_Expecter struct {
	mock *mock.Mock
}

func (_m *WebhooksRoutesIF) EXPECT() *WebhooksRoutesIF_Expecter {
	return &WebhooksRoutesIF_Expecter{mock: &_m.Mock}
}

// Resource provides a mock function with given fields: c
func (_m *WebhooksRoutesIF) Resource(c *echo.Group) {
	_m.Called(c)
}

// WebhooksRoutesIF_Resource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resource'
type WebhooksRoutesIF_Resource_Call struct {
	*mock.Call
}

// Resource is a helper method to define mock.On call
//   - c *echo.Group
func (_e *WebhooksRoutesIF_Expecter) Resource(c interface{}) *WebhooksRoutesIF_Resource_Call {
	return &WebhooksRoutesIF_Resource_Call{Call: _e.mock.On("Resource", c)}
}

func (_c *WebhooksRoutesIF_Resource_Call) Run(run func(c *echo.Group)) *WebhooksRoutesIF_Resource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*echo.Group))
	})
	return _c
}

func (_c *WebhooksRoutesIF_Resource_Call) Return() *WebhooksRoutesIF_Resource_Call {
	_c.Call.Return()
	return _c
}

func (_c *WebhooksRoutesIF_Resource_Call) RunAndReturn(run func(*echo.Group)) *WebhooksRoutesIF_Resource_Call {
	_c.Run(run)
	return _c
}

// NewWebhooksRoutesIF creates a new instance of WebhooksRoutesIF. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWebhooksRoutesIF(t interface {
	mock.TestingT
	Cleanup(func())
}) *WebhooksRoutesIF {
	mock := &WebhooksRoutesIF{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
