// Code generated by mockery. DO NOT EDIT.

package card

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// DeleteCardHandlerIF is an autogenerated mock type for the DeleteCardHandlerIF type
type DeleteCardHandlerIF struct {
	mock.Mock
}

type DeleteCardHandlerIF_Expecter struct {
	mock *mock.Mock
}

func (_m *DeleteCardHandlerIF) EXPECT() *DeleteCardHandlerIF_Expecter {
	return &DeleteCardHandlerIF_Expecter{mock: &_m.Mock}
}

// DeleteCard provides a mock function with given fields: context
func (_m *DeleteCardHandlerIF) DeleteCard(context echo.Context) error {
	ret := _m.Called(context)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCard")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(context)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteCardHandlerIF_DeleteCard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCard'
type DeleteCardHandlerIF_DeleteCard_Call struct {
	*mock.Call
}

// DeleteCard is a helper method to define mock.On call
//   - context echo.Context
func (_e *DeleteCardHandlerIF_Expecter) DeleteCard(context interface{}) *DeleteCardHandlerIF_DeleteCard_Call {
	return &DeleteCardHandlerIF_DeleteCard_Call{Call: _e.mock.On("DeleteCard", context)}
}

func (_c *DeleteCardHandlerIF_DeleteCard_Call) Run(run func(context echo.Context)) *DeleteCardHandlerIF_DeleteCard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *DeleteCardHandlerIF_DeleteCard_Call) Return(_a0 error) *DeleteCardHandlerIF_DeleteCard_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DeleteCardHandlerIF_DeleteCard_Call) RunAndReturn(run func(echo.Context) error) *DeleteCardHandlerIF_DeleteCard_Call {
	_c.Call.Return(run)
	return _c
}

// NewDeleteCardHandlerIF creates a new instance of DeleteCardHandlerIF. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeleteCardHandlerIF(t interface {
	mock.TestingT
	Cleanup(func())
}) *DeleteCardHandlerIF {
	mock := &DeleteCardHandlerIF{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
