// Code generated by mockery. DO NOT EDIT.

package webhooks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// WebhooksHandlerIF is an autogenerated mock type for the WebhooksHandlerIF type
type WebhooksHandlerIF struct {
	mock.Mock
}

type WebhooksHandlerIF_Expecter struct {
	mock *mock.Mock
}

func (_m *WebhooksHandlerIF) EXPECT() *WebhooksHandlerIF_Expecter {
	return &WebhooksHandlerIF_Expecter{mock: &_m.Mock}
}

// DeunaWebhookNotifyOrder provides a mock function with given fields: context
func (_m *WebhooksHandlerIF) DeunaWebhookNotifyOrder(context echo.Context) error {
	ret := _m.Called(context)

	if len(ret) == 0 {
		panic("no return value specified for DeunaWebhookNotifyOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(context)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WebhooksHandlerIF_DeunaWebhookNotifyOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeunaWebhookNotifyOrder'
type WebhooksHandlerIF_DeunaWebhookNotifyOrder_Call struct {
	*mock.Call
}

// DeunaWebhookNotifyOrder is a helper method to define mock.On call
//   - context echo.Context
func (_e *WebhooksHandlerIF_Expecter) DeunaWebhookNotifyOrder(context interface{}) *WebhooksHandlerIF_DeunaWebhookNotifyOrder_Call {
	return &WebhooksHandlerIF_DeunaWebhookNotifyOrder_Call{Call: _e.mock.On("DeunaWebhookNotifyOrder", context)}
}

func (_c *WebhooksHandlerIF_DeunaWebhookNotifyOrder_Call) Run(run func(context echo.Context)) *WebhooksHandlerIF_DeunaWebhookNotifyOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *WebhooksHandlerIF_DeunaWebhookNotifyOrder_Call) Return(_a0 error) *WebhooksHandlerIF_DeunaWebhookNotifyOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WebhooksHandlerIF_DeunaWebhookNotifyOrder_Call) RunAndReturn(run func(echo.Context) error) *WebhooksHandlerIF_DeunaWebhookNotifyOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewWebhooksHandlerIF creates a new instance of WebhooksHandlerIF. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWebhooksHandlerIF(t interface {
	mock.TestingT
	Cleanup(func())
}) *WebhooksHandlerIF {
	mock := &WebhooksHandlerIF{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
