// Code generated by mockery. DO NOT EDIT.

package create

import (
	context "context"

	command "gitlab.com/clubhub.ai1/organization/backend/payments-api/internal/domain/order/command"

	mock "github.com/stretchr/testify/mock"

	response "gitlab.com/clubhub.ai1/organization/backend/payments-api/internal/infra/api/handler/order/dto/response"
)

// CreateOrderUseCaseIF is an autogenerated mock type for the CreateOrderUseCaseIF type
type CreateOrderUseCaseIF struct {
	mock.Mock
}

type CreateOrderUseCaseIF_Expecter struct {
	mock *mock.Mock
}

func (_m *CreateOrderUseCaseIF) EXPECT() *CreateOrderUseCaseIF_Expecter {
	return &CreateOrderUseCaseIF_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, cmd
func (_m *CreateOrderUseCaseIF) Create(ctx context.Context, cmd command.CreateOrderCommand) (response.OrderResponseDTO, error) {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 response.OrderResponseDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, command.CreateOrderCommand) (response.OrderResponseDTO, error)); ok {
		return rf(ctx, cmd)
	}
	if rf, ok := ret.Get(0).(func(context.Context, command.CreateOrderCommand) response.OrderResponseDTO); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Get(0).(response.OrderResponseDTO)
	}

	if rf, ok := ret.Get(1).(func(context.Context, command.CreateOrderCommand) error); ok {
		r1 = rf(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateOrderUseCaseIF_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type CreateOrderUseCaseIF_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd command.CreateOrderCommand
func (_e *CreateOrderUseCaseIF_Expecter) Create(ctx interface{}, cmd interface{}) *CreateOrderUseCaseIF_Create_Call {
	return &CreateOrderUseCaseIF_Create_Call{Call: _e.mock.On("Create", ctx, cmd)}
}

func (_c *CreateOrderUseCaseIF_Create_Call) Run(run func(ctx context.Context, cmd command.CreateOrderCommand)) *CreateOrderUseCaseIF_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(command.CreateOrderCommand))
	})
	return _c
}

func (_c *CreateOrderUseCaseIF_Create_Call) Return(_a0 response.OrderResponseDTO, _a1 error) *CreateOrderUseCaseIF_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CreateOrderUseCaseIF_Create_Call) RunAndReturn(run func(context.Context, command.CreateOrderCommand) (response.OrderResponseDTO, error)) *CreateOrderUseCaseIF_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewCreateOrderUseCaseIF creates a new instance of CreateOrderUseCaseIF. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCreateOrderUseCaseIF(t interface {
	mock.TestingT
	Cleanup(func())
}) *CreateOrderUseCaseIF {
	mock := &CreateOrderUseCaseIF{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
