// Code generated by mockery. DO NOT EDIT.

package payment_concept

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// PaymentConceptHandlerIF is an autogenerated mock type for the PaymentConceptHandlerIF type
type PaymentConceptHandlerIF struct {
	mock.Mock
}

type PaymentConceptHandlerIF_Expecter struct {
	mock *mock.Mock
}

func (_m *PaymentConceptHandlerIF) EXPECT() *PaymentConceptHandlerIF_Expecter {
	return &PaymentConceptHandlerIF_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: context
func (_m *PaymentConceptHandlerIF) Create(context echo.Context) error {
	ret := _m.Called(context)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(context)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PaymentConceptHandlerIF_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type PaymentConceptHandlerIF_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context echo.Context
func (_e *PaymentConceptHandlerIF_Expecter) Create(context interface{}) *PaymentConceptHandlerIF_Create_Call {
	return &PaymentConceptHandlerIF_Create_Call{Call: _e.mock.On("Create", context)}
}

func (_c *PaymentConceptHandlerIF_Create_Call) Run(run func(context echo.Context)) *PaymentConceptHandlerIF_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *PaymentConceptHandlerIF_Create_Call) Return(_a0 error) *PaymentConceptHandlerIF_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PaymentConceptHandlerIF_Create_Call) RunAndReturn(run func(echo.Context) error) *PaymentConceptHandlerIF_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewPaymentConceptHandlerIF creates a new instance of PaymentConceptHandlerIF. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentConceptHandlerIF(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentConceptHandlerIF {
	mock := &PaymentConceptHandlerIF{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
