// Code generated by mockery. DO NOT EDIT.

package pdf_generator

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"

	interfaces "gitlab.com/clubhub.ai1/organization/backend/payments-api/internal/application/payment_receipt/interfaces"
)

// ReceiptPaymentGenerator is an autogenerated mock type for the ReceiptPaymentGenerator type
type ReceiptPaymentGenerator struct {
	mock.Mock
}

type ReceiptPaymentGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *ReceiptPaymentGenerator) EXPECT() *ReceiptPaymentGenerator_Expecter {
	return &ReceiptPaymentGenerator_Expecter{mock: &_m.Mock}
}

// GenerateReceiptPaymentPDF provides a mock function with given fields: ctx, receiptData
func (_m *ReceiptPaymentGenerator) GenerateReceiptPaymentPDF(ctx context.Context, receiptData interfaces.ReceiptData) (io.Reader, error) {
	ret := _m.Called(ctx, receiptData)

	if len(ret) == 0 {
		panic("no return value specified for GenerateReceiptPaymentPDF")
	}

	var r0 io.Reader
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, interfaces.ReceiptData) (io.Reader, error)); ok {
		return rf(ctx, receiptData)
	}
	if rf, ok := ret.Get(0).(func(context.Context, interfaces.ReceiptData) io.Reader); ok {
		r0 = rf(ctx, receiptData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Reader)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, interfaces.ReceiptData) error); ok {
		r1 = rf(ctx, receiptData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReceiptPaymentGenerator_GenerateReceiptPaymentPDF_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateReceiptPaymentPDF'
type ReceiptPaymentGenerator_GenerateReceiptPaymentPDF_Call struct {
	*mock.Call
}

// GenerateReceiptPaymentPDF is a helper method to define mock.On call
//   - ctx context.Context
//   - receiptData interfaces.ReceiptData
func (_e *ReceiptPaymentGenerator_Expecter) GenerateReceiptPaymentPDF(ctx interface{}, receiptData interface{}) *ReceiptPaymentGenerator_GenerateReceiptPaymentPDF_Call {
	return &ReceiptPaymentGenerator_GenerateReceiptPaymentPDF_Call{Call: _e.mock.On("GenerateReceiptPaymentPDF", ctx, receiptData)}
}

func (_c *ReceiptPaymentGenerator_GenerateReceiptPaymentPDF_Call) Run(run func(ctx context.Context, receiptData interfaces.ReceiptData)) *ReceiptPaymentGenerator_GenerateReceiptPaymentPDF_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interfaces.ReceiptData))
	})
	return _c
}

func (_c *ReceiptPaymentGenerator_GenerateReceiptPaymentPDF_Call) Return(_a0 io.Reader, _a1 error) *ReceiptPaymentGenerator_GenerateReceiptPaymentPDF_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReceiptPaymentGenerator_GenerateReceiptPaymentPDF_Call) RunAndReturn(run func(context.Context, interfaces.ReceiptData) (io.Reader, error)) *ReceiptPaymentGenerator_GenerateReceiptPaymentPDF_Call {
	_c.Call.Return(run)
	return _c
}

// NewReceiptPaymentGenerator creates a new instance of ReceiptPaymentGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReceiptPaymentGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReceiptPaymentGenerator {
	mock := &ReceiptPaymentGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
