// Code generated by mockery. DO NOT EDIT.

package order

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// OrderPaymentsHandlerIF is an autogenerated mock type for the OrderPaymentsHandlerIF type
type OrderPaymentsHandlerIF struct {
	mock.Mock
}

type OrderPaymentsHandlerIF_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderPaymentsHandlerIF) EXPECT() *OrderPaymentsHandlerIF_Expecter {
	return &OrderPaymentsHandlerIF_Expecter{mock: &_m.Mock}
}

// Pay provides a mock function with given fields: context
func (_m *OrderPaymentsHandlerIF) Pay(context echo.Context) error {
	ret := _m.Called(context)

	if len(ret) == 0 {
		panic("no return value specified for Pay")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(context)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrderPaymentsHandlerIF_Pay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pay'
type OrderPaymentsHandlerIF_Pay_Call struct {
	*mock.Call
}

// Pay is a helper method to define mock.On call
//   - context echo.Context
func (_e *OrderPaymentsHandlerIF_Expecter) Pay(context interface{}) *OrderPaymentsHandlerIF_Pay_Call {
	return &OrderPaymentsHandlerIF_Pay_Call{Call: _e.mock.On("Pay", context)}
}

func (_c *OrderPaymentsHandlerIF_Pay_Call) Run(run func(context echo.Context)) *OrderPaymentsHandlerIF_Pay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *OrderPaymentsHandlerIF_Pay_Call) Return(_a0 error) *OrderPaymentsHandlerIF_Pay_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderPaymentsHandlerIF_Pay_Call) RunAndReturn(run func(echo.Context) error) *OrderPaymentsHandlerIF_Pay_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderPaymentsHandlerIF creates a new instance of OrderPaymentsHandlerIF. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderPaymentsHandlerIF(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderPaymentsHandlerIF {
	mock := &OrderPaymentsHandlerIF{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
