// Code generated by mockery. DO NOT EDIT.

package order

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// PaymentRefundHandlerIF is an autogenerated mock type for the PaymentRefundHandlerIF type
type PaymentRefundHandlerIF struct {
	mock.Mock
}

type PaymentRefundHandlerIF_Expecter struct {
	mock *mock.Mock
}

func (_m *PaymentRefundHandlerIF) EXPECT() *PaymentRefundHandlerIF_Expecter {
	return &PaymentRefundHandlerIF_Expecter{mock: &_m.Mock}
}

// Refund provides a mock function with given fields: context
func (_m *PaymentRefundHandlerIF) Refund(context echo.Context) error {
	ret := _m.Called(context)

	if len(ret) == 0 {
		panic("no return value specified for Refund")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(context)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PaymentRefundHandlerIF_Refund_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refund'
type PaymentRefundHandlerIF_Refund_Call struct {
	*mock.Call
}

// Refund is a helper method to define mock.On call
//   - context echo.Context
func (_e *PaymentRefundHandlerIF_Expecter) Refund(context interface{}) *PaymentRefundHandlerIF_Refund_Call {
	return &PaymentRefundHandlerIF_Refund_Call{Call: _e.mock.On("Refund", context)}
}

func (_c *PaymentRefundHandlerIF_Refund_Call) Run(run func(context echo.Context)) *PaymentRefundHandlerIF_Refund_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *PaymentRefundHandlerIF_Refund_Call) Return(_a0 error) *PaymentRefundHandlerIF_Refund_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PaymentRefundHandlerIF_Refund_Call) RunAndReturn(run func(echo.Context) error) *PaymentRefundHandlerIF_Refund_Call {
	_c.Call.Return(run)
	return _c
}

// NewPaymentRefundHandlerIF creates a new instance of PaymentRefundHandlerIF. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentRefundHandlerIF(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentRefundHandlerIF {
	mock := &PaymentRefundHandlerIF{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
