// Code generated by mockery. DO NOT EDIT.

package repository

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entities "gitlab.com/clubhub.ai1/organization/backend/payments-api/internal/infra/repositories/refund/entities"
)

// RefundWriteRepositoryIF is an autogenerated mock type for the RefundWriteRepositoryIF type
type RefundWriteRepositoryIF struct {
	mock.Mock
}

type RefundWriteRepositoryIF_Expecter struct {
	mock *mock.Mock
}

func (_m *RefundWriteRepositoryIF) EXPECT() *RefundWriteRepositoryIF_Expecter {
	return &RefundWriteRepositoryIF_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, refund
func (_m *RefundWriteRepositoryIF) Create(ctx context.Context, refund entities.RefundEntity) error {
	ret := _m.Called(ctx, refund)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.RefundEntity) error); ok {
		r0 = rf(ctx, refund)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RefundWriteRepositoryIF_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type RefundWriteRepositoryIF_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - refund entities.RefundEntity
func (_e *RefundWriteRepositoryIF_Expecter) Create(ctx interface{}, refund interface{}) *RefundWriteRepositoryIF_Create_Call {
	return &RefundWriteRepositoryIF_Create_Call{Call: _e.mock.On("Create", ctx, refund)}
}

func (_c *RefundWriteRepositoryIF_Create_Call) Run(run func(ctx context.Context, refund entities.RefundEntity)) *RefundWriteRepositoryIF_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entities.RefundEntity))
	})
	return _c
}

func (_c *RefundWriteRepositoryIF_Create_Call) Return(_a0 error) *RefundWriteRepositoryIF_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RefundWriteRepositoryIF_Create_Call) RunAndReturn(run func(context.Context, entities.RefundEntity) error) *RefundWriteRepositoryIF_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewRefundWriteRepositoryIF creates a new instance of RefundWriteRepositoryIF. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRefundWriteRepositoryIF(t interface {
	mock.TestingT
	Cleanup(func())
}) *RefundWriteRepositoryIF {
	mock := &RefundWriteRepositoryIF{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
