// Code generated by mockery. DO NOT EDIT.

package release

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// ReleaseHandlerIF is an autogenerated mock type for the ReleaseHandlerIF type
type ReleaseHandlerIF struct {
	mock.Mock
}

type ReleaseHandlerIF_Expecter struct {
	mock *mock.Mock
}

func (_m *ReleaseHandlerIF) EXPECT() *ReleaseHandlerIF_Expecter {
	return &ReleaseHandlerIF_Expecter{mock: &_m.Mock}
}

// ReleasePayment provides a mock function with given fields: context
func (_m *ReleaseHandlerIF) ReleasePayment(context echo.Context) error {
	ret := _m.Called(context)

	if len(ret) == 0 {
		panic("no return value specified for ReleasePayment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(context)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReleaseHandlerIF_ReleasePayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReleasePayment'
type ReleaseHandlerIF_ReleasePayment_Call struct {
	*mock.Call
}

// ReleasePayment is a helper method to define mock.On call
//   - context echo.Context
func (_e *ReleaseHandlerIF_Expecter) ReleasePayment(context interface{}) *ReleaseHandlerIF_ReleasePayment_Call {
	return &ReleaseHandlerIF_ReleasePayment_Call{Call: _e.mock.On("ReleasePayment", context)}
}

func (_c *ReleaseHandlerIF_ReleasePayment_Call) Run(run func(context echo.Context)) *ReleaseHandlerIF_ReleasePayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *ReleaseHandlerIF_ReleasePayment_Call) Return(_a0 error) *ReleaseHandlerIF_ReleasePayment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ReleaseHandlerIF_ReleasePayment_Call) RunAndReturn(run func(echo.Context) error) *ReleaseHandlerIF_ReleasePayment_Call {
	_c.Call.Return(run)
	return _c
}

// NewReleaseHandlerIF creates a new instance of ReleaseHandlerIF. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReleaseHandlerIF(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReleaseHandlerIF {
	mock := &ReleaseHandlerIF{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
