// Code generated by mockery. DO NOT EDIT.

package value_objects

import mock "github.com/stretchr/testify/mock"

// SupportedPaymentMethod is an autogenerated mock type for the SupportedPaymentMethod type
type SupportedPaymentMethod struct {
	mock.Mock
}

type SupportedPaymentMethod_Expecter struct {
	mock *mock.Mock
}

func (_m *SupportedPaymentMethod) EXPECT() *SupportedPaymentMethod_Expecter {
	return &SupportedPaymentMethod_Expecter{mock: &_m.Mock}
}

// Validate provides a mock function with no fields
func (_m *SupportedPaymentMethod) Validate() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SupportedPaymentMethod_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type SupportedPaymentMethod_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
func (_e *SupportedPaymentMethod_Expecter) Validate() *SupportedPaymentMethod_Validate_Call {
	return &SupportedPaymentMethod_Validate_Call{Call: _e.mock.On("Validate")}
}

func (_c *SupportedPaymentMethod_Validate_Call) Run(run func()) *SupportedPaymentMethod_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SupportedPaymentMethod_Validate_Call) Return(_a0 error) *SupportedPaymentMethod_Validate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SupportedPaymentMethod_Validate_Call) RunAndReturn(run func() error) *SupportedPaymentMethod_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// NewSupportedPaymentMethod creates a new instance of SupportedPaymentMethod. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSupportedPaymentMethod(t interface {
	mock.TestingT
	Cleanup(func())
}) *SupportedPaymentMethod {
	mock := &SupportedPaymentMethod{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
