// Code generated by mockery. DO NOT EDIT.

package value_objects

import mock "github.com/stretchr/testify/mock"

// SupportedPaymentMethodIF is an autogenerated mock type for the SupportedPaymentMethodIF type
type SupportedPaymentMethodIF struct {
	mock.Mock
}

type SupportedPaymentMethodIF_Expecter struct {
	mock *mock.Mock
}

func (_m *SupportedPaymentMethodIF) EXPECT() *SupportedPaymentMethodIF_Expecter {
	return &SupportedPaymentMethodIF_Expecter{mock: &_m.Mock}
}

// Validate provides a mock function with no fields
func (_m *SupportedPaymentMethodIF) Validate() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SupportedPaymentMethodIF_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type SupportedPaymentMethodIF_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
func (_e *SupportedPaymentMethodIF_Expecter) Validate() *SupportedPaymentMethodIF_Validate_Call {
	return &SupportedPaymentMethodIF_Validate_Call{Call: _e.mock.On("Validate")}
}

func (_c *SupportedPaymentMethodIF_Validate_Call) Run(run func()) *SupportedPaymentMethodIF_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SupportedPaymentMethodIF_Validate_Call) Return(_a0 error) *SupportedPaymentMethodIF_Validate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SupportedPaymentMethodIF_Validate_Call) RunAndReturn(run func() error) *SupportedPaymentMethodIF_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// NewSupportedPaymentMethodIF creates a new instance of SupportedPaymentMethodIF. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSupportedPaymentMethodIF(t interface {
	mock.TestingT
	Cleanup(func())
}) *SupportedPaymentMethodIF {
	mock := &SupportedPaymentMethodIF{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
