// Code generated by mockery. DO NOT EDIT.

package adapters

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "gitlab.com/clubhub.ai1/organization/backend/payments-api/internal/application/refund/adapters/models"
	response "gitlab.com/clubhub.ai1/organization/backend/payments-api/internal/infra/api/handler/order/dto/response"
)

// PartialRefundAdapterIF is an autogenerated mock type for the PartialRefundAdapterIF type
type PartialRefundAdapterIF struct {
	mock.Mock
}

type PartialRefundAdapterIF_Expecter struct {
	mock *mock.Mock
}

func (_m *PartialRefundAdapterIF) EXPECT() *PartialRefundAdapterIF_Expecter {
	return &PartialRefundAdapterIF_Expecter{mock: &_m.Mock}
}

// PartialRefund provides a mock function with given fields: ctx, refund, refundReason
func (_m *PartialRefundAdapterIF) PartialRefund(ctx context.Context, refund models.RefundAdapterModel, refundReason string) (response.RefundResponseDTO, error) {
	ret := _m.Called(ctx, refund, refundReason)

	if len(ret) == 0 {
		panic("no return value specified for PartialRefund")
	}

	var r0 response.RefundResponseDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.RefundAdapterModel, string) (response.RefundResponseDTO, error)); ok {
		return rf(ctx, refund, refundReason)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.RefundAdapterModel, string) response.RefundResponseDTO); ok {
		r0 = rf(ctx, refund, refundReason)
	} else {
		r0 = ret.Get(0).(response.RefundResponseDTO)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.RefundAdapterModel, string) error); ok {
		r1 = rf(ctx, refund, refundReason)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PartialRefundAdapterIF_PartialRefund_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PartialRefund'
type PartialRefundAdapterIF_PartialRefund_Call struct {
	*mock.Call
}

// PartialRefund is a helper method to define mock.On call
//   - ctx context.Context
//   - refund models.RefundAdapterModel
//   - refundReason string
func (_e *PartialRefundAdapterIF_Expecter) PartialRefund(ctx interface{}, refund interface{}, refundReason interface{}) *PartialRefundAdapterIF_PartialRefund_Call {
	return &PartialRefundAdapterIF_PartialRefund_Call{Call: _e.mock.On("PartialRefund", ctx, refund, refundReason)}
}

func (_c *PartialRefundAdapterIF_PartialRefund_Call) Run(run func(ctx context.Context, refund models.RefundAdapterModel, refundReason string)) *PartialRefundAdapterIF_PartialRefund_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.RefundAdapterModel), args[2].(string))
	})
	return _c
}

func (_c *PartialRefundAdapterIF_PartialRefund_Call) Return(_a0 response.RefundResponseDTO, _a1 error) *PartialRefundAdapterIF_PartialRefund_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PartialRefundAdapterIF_PartialRefund_Call) RunAndReturn(run func(context.Context, models.RefundAdapterModel, string) (response.RefundResponseDTO, error)) *PartialRefundAdapterIF_PartialRefund_Call {
	_c.Call.Return(run)
	return _c
}

// NewPartialRefundAdapterIF creates a new instance of PartialRefundAdapterIF. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPartialRefundAdapterIF(t interface {
	mock.TestingT
	Cleanup(func())
}) *PartialRefundAdapterIF {
	mock := &PartialRefundAdapterIF{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
